[package]
name = "aoc"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
path = "lib.rs"

[[bin]]
name = "day1"
path = "day1.rs"

[dependencies]
anyhow = "1.0.51"
ureq = "2.3.1"
